/* BC MOTT Radio — Call Sign Directory
 * Service worker
 *
 * Written 27 August 2026 to match the contract index.html already expects:
 *
 *     it sends  { type: "refresh" }   and waits for  { type: "refreshed" }
 *     it sends  "skipWaiting"         (a bare string, not an object)
 *     it registers  ./sw.js           (relative — works under a /repo/ path)
 *
 * WHY THIS FILE EXISTS
 * The app detects a new release correctly: version.json is fetched with
 * no-store and compared against the build the device last accepted. But
 * DETECTING is not APPLYING — applying is this worker's job, and if the worker
 * keeps serving the copy it already cached, the app reloads and shows the old
 * page while recording the new build id. The prompt then never returns, because
 * the stored id matches. That is the "it refreshed but the date is still old"
 * symptom.
 *
 * THE RULE THAT MATTERS
 * On { type: "refresh" } this worker re-fetches the shell with cache: "no-store"
 * — going past the HTTP cache to the network — writes it into the cache, and
 * only THEN replies "refreshed". The page reloads into fresh content rather than
 * into whatever was already there.
 *
 * WHY SHELL LEADS WITH './'
 * The live address is a directory - https://bcgov.github.io/TTRCB/ - so the
 * navigation request is for './' while the file is cached as './index.html'.
 * Those are two cache keys for the same bytes. If only the filename gets
 * refreshed, the reload after the update button serves the OLD copy from the
 * './' entry and the build date appears not to have changed. Both must be in
 * SHELL. This is why the first entry is not redundant.
 *
 * THIS FILE IS GENERATED by build_static_callbook.py. Edit it THERE. A hand
 * edit here is overwritten by the next build - which is exactly how an
 * earlier, better version of this worker was silently lost.
 *
 * OFFLINE IS THE POINT OF THIS PRODUCT
 * A crew in a dead zone must still get the directory. So navigations are served
 * cache-first and the network is only consulted to refresh in the background.
 * Never make navigation network-first: it puts a timeout between a driver and a
 * phone number at exactly the moment the signal is bad.
 *
 * BUMPING FOR A RELEASE
 * Change CACHE below. Anything different works; the date is for humans reading
 * the repo. An unchanged CACHE means old caches are never cleaned up — the
 * refresh path still works, but stale copies accumulate.
 */

const CACHE = "rcb-02September2026";

/* Everything needed to open the app with no signal at all. Keep this list in
 * step with the deployment set; a missing file here fails silently offline. */
const SHELL = [
  './',
  "./index.html",
  './rcb-b3.webmanifest',
  './manifest.webmanifest',
  './rcb-icon-b2-192.png',
  './rcb-icon-b2-512.png'
];

/* version.json must NEVER be cached — it is the freshness signal itself. */
const NEVER_CACHE = /version\.json(\?|$)/;

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    /* addAll() rejects the whole install if any single file 404s, which would
     * leave the app with no worker at all. Add them individually so one missing
     * icon cannot take the directory offline. */
    await Promise.all(SHELL.map(async (url) => {
      try {
        const res = await fetch(url, { cache: 'no-store' });
        if (res && res.ok) await cache.put(url, res.clone());
      } catch (e) { /* offline at install: the fetch handler will fill it in */ }
    }));
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names.map((n) => (n === CACHE ? null : caches.delete(n))));
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;

  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  /* Freshness signal: always straight to the network, never stored. */
  if (NEVER_CACHE.test(url.pathname + url.search)) {
    event.respondWith(fetch(req, { cache: 'no-store' }).catch(() => Response.error()));
    return;
  }

  /* Navigations: cache-first, so a dead zone still opens the directory.
   * A background fetch keeps the cached copy warm for next time. */
  if (req.mode === 'navigate') {
    event.respondWith((async () => {
      const cache = await caches.open(CACHE);
      const hit = await cache.match("./index.html");
      if (hit) {
        event.waitUntil(refreshShell(cache).catch(() => {}));
        return hit;
      }
      try {
        const res = await fetch(req);
        if (res && res.ok) cache.put("./index.html", res.clone());
        return res;
      } catch (e) {
        return new Response('Offline and no cached copy is stored yet.', {
          status: 503, headers: { 'Content-Type': 'text/plain' }
        });
      }
    })());
    return;
  }

  /* Everything else: cache-first, fall back to network, store what succeeds. */
  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const hit = await cache.match(req);
    if (hit) return hit;
    try {
      const res = await fetch(req);
      if (res && res.ok && res.type === 'basic') cache.put(req, res.clone());
      return res;
    } catch (e) {
      return hit || Response.error();
    }
  })());
});

/* Re-fetch the shell past every cache layer and store it. */
async function refreshShell(cache) {
  const res = await fetch("./index.html", { cache: 'no-store' });
  if (res && res.ok) await cache.put("./index.html", res.clone());
  return res;
}

self.addEventListener('message', (event) => {
  const data = event.data;

  /* Sent as a bare string by the update-detection path in index.html. */
  if (data === 'skipWaiting') { self.skipWaiting(); return; }

  if (data && data.type === 'refresh') {
    event.waitUntil((async () => {
      try {
        const cache = await caches.open(CACHE);
        await refreshShell(cache);
        /* Re-prime the rest of the shell too, so icons and the manifest do not
         * lag a release behind the page that references them. */
        await Promise.all(SHELL.filter((u) => u !== "./index.html").map(
          async (u) => {
            try {
              const r = await fetch(u, { cache: 'no-store' });
              if (r && r.ok) await cache.put(u, r.clone());
            } catch (e) { /* one missing asset must not block the reply */ }
          }));
      } catch (e) { /* fall through — reply anyway so the app never hangs */ }

      /* Reply to EVERY client. The app also has a 6-second fallback that
       * reloads regardless; if this reply never arrived, the reload would land
       * on the old cached page and the app would then record the new build id
       * against stale content — the exact failure this file exists to stop. */
      const clients = await self.clients.matchAll({ includeUncontrolled: true });
      clients.forEach((c) => {
        try { c.postMessage({ type: 'refreshed' }); } catch (e) {}
      });
    })());
  }
});
